---
title: "app"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Create analytical dataset for application


```{r read.data}
# read data
labs = read.csv("labsum.csv") # CD4, etc.
f22r = read.csv('f22r.csv') # f22r.csv: new recruit antiviral medication history
drug1 = read.csv('drug1.csv') # drug1.csv: antiviral medications
drugmap = read.csv('drugmap.csv', stringsAsFactors = FALSE) # drug code to classification
el = read.csv("el.csv") # baseline covariates
```


```{r cases}
# subset to HIV + patients who have not taken an antiviral (EMTXDR=2)
# filter out HIV negative patients (maindr != 1)

f22r.f = f22r %>% filter(EMTXDR == 2, MAINDR != 1)
drug1.f = drug1 %>% filter(CASEID %in% f22r.f$CASEID) # CASES
# let's look at these treatment sequences/ how much data do we have here 
case.vis = drug1.f %>% group_by(CASEID, VISIT) %>% 
  summarise(n=n()) %>% mutate(start = min(VISIT)) %>% arrange(CASEID, VISIT)

# now, let's look at the kinds of drugs we observe in these sequences
which.drugs = inner_join(case.vis, drug1.f, by = c("CASEID", "VISIT")) %>%
  left_join(drugmap, by = c("DRUGD1"="Num")) %>% 
  dplyr::select(CASEID, VISIT, DRUGD1, Class)

l = which.drugs %>% group_by(CASEID, VISIT) %>% group_map(~ unique(.x$Class))

# lapply a function 

# l is a character vector with at least two elements
dosage = function(l) {
  
  if(length(l) == 1) {return(l)} else {
  
  if ( "NNRTI" %in% l & "NRTI" %in% l ) {
    return("NRTI + NNRTI")
  } else if ( "NNRTI" %in% l & "PI" %in% l ) {
    return("NNRTI + PI")
  } else if ( "NRTI" %in% l & "PI" %in% l ) {
    return("NRTI + PI")
  } else if ( "NRTI" %in% l & "II" %in% l ) {
    return("NRTI + II")
  } else {return("All")} }
}

case.vis$class = unlist( lapply(l, dosage) )
case.vis$id = sapply(case.vis$CASEID, function(x) which(unique(case.vis$CASEID)==x))
case.vis2 = case.vis %>% group_by(CASEID) %>% mutate(t = VISIT - min(VISIT))

# coarsen treatment
case.vis2$class2 = ifelse(case.vis2$class == "NRTI", "ART", "HAART")

# make dataframe that has the sequence of visits we are interested in for each patient
minv = case.vis2 %>% group_by(CASEID) %>% summarise(`1` = min(VISIT))
minv$`0` = minv$`1` - 1
minv$`2` = minv$`1` + 1
minv$`3` = minv$`1` + 2
minv$`4` = minv$`1` + 3
minv.l = minv %>% pivot_longer(!CASEID, values_to = "VISIT")

labsdat = left_join(minv.l, labs, by = c("CASEID", "VISIT")) %>% group_by(CASEID) %>% arrange(CASEID, VISIT)  %>%
  mutate(t = 1:n()) %>% left_join(case.vis2, by = c("CASEID", "VISIT")) %>%
  select(CASEID, VISIT, VLOAD, CD4N, CD8N, CD3N, HSRAT, t.x, class2)

# let's filter to people who have an observed outcome (time 4)
outcome.cohort = labsdat %>% filter(t.x==3) %>% filter(!is.na(VLOAD))

labsdat$A = ifelse(is.na(labsdat$class2), 0 , 1)

labsdat.f = labsdat %>% filter(t.x < 4, CASEID %in% outcome.cohort$CASEID) %>%
            group_by(CASEID) %>% mutate(A2 = c(A[2:3], NA))

```

```{r controls}
# subset to HIV + patients who have not taken an antiviral (EMTXDR=2)
# filter out HIV negative patients (maindr != 1)

f22r.f = f22r %>% filter(EMTXDR == 2, MAINDR != 1)
drug1.f = drug1 %>% filter(CASEID %in% f22r.f$CASEID) # CASES

# ID not in cases AND min visit is 15,16 (same cohort as most of the cases)
# important data is the lab data
labs.control = labs %>% filter( !(CASEID %in% unique(drug1.f$CASEID)) ) %>% 
  group_by(CASEID) %>% mutate(mvis = min(VISIT)) %>% filter(mvis %in% c(15,16)) %>%
  select(CASEID, VISIT, VLOAD, CD4N, CD8N, CD3N, HSRAT) %>% mutate(d = c(0,diff(VISIT))) %>% 
  filter(d == 1) %>% group_by(CASEID) %>% slice_head(n=3) %>% mutate(d2 = c(1,diff(VISIT))) %>% 
  mutate(sumd = sum(d2)) %>% filter(sumd == 3)
```


```{r}
# compare baseline measurements across case/ control

labsdat.control = labs.control %>% select(CASEID, VISIT, VLOAD, CD4N, CD8N, CD3N, HSRAT) %>%
                  mutate(type = "control", A = 0, A2 = 0)

labsdat.case = labsdat.f %>% select(CASEID, VISIT, VLOAD, CD4N, CD8N, CD3N, HSRAT, A, A2) %>%
                  mutate(type = "case")

combined = rbind(labsdat.control, labsdat.case)

plotter = combined %>% group_by(CASEID) %>% slice_head(n=1)

#ggplot(plotter, aes(x = log(VLOAD), group = type)) + geom_histogram(aes(color = type))

p1 = ggplot(plotter, aes(x=log(VLOAD), color=type, fill=type)) +
  geom_histogram(position="identity", alpha=0.5, bins = 30) +
  scale_color_manual(values=c("#999999", "#E69F00")) +
  scale_fill_manual(values=c("#999999", "#E69F00")) +
  labs(title="Weight histogram plot",x="Log(Viral Load)", y = "Count") +
  theme_classic()

p2 = ggplot(plotter, aes(x=log(CD4N), color=type, fill=type)) +
  geom_histogram(position="identity", alpha=0.5, bins = 30) +
  scale_color_manual(values=c("#999999", "#E69F00")) +
  scale_fill_manual(values=c("#999999", "#E69F00")) +
  labs(title="Log(CD4 Count)",x="Log(CD4 Count)", y = "Count") +
  theme_classic()

```

# TO DO
# to do - distribution of baseline: case versus control: CHECK
# is there a viral load threshold?

```{r}
# can we discretize the viral load variable

#combined$VLOAD2 = cut(disc$VLOAD, breaks = c(0, 80, 200, 1000000))
combined$VLOAD2 = ifelse(combined$VLOAD > exp(10), 1, 0)
summary(glm(A2 ~ (VLOAD2), family = binomial, data = combined))

```

```{r}


```

