---
title: "format.data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mice)
library(mvtnorm)
```

## Format data for analysis

```{r}
simple.analysis = combined %>% select(CASEID, VISIT, CD4N, A2, CD8N) %>% 
  group_by(CASEID) %>% mutate(nv = VISIT - min(VISIT))

dat = simple.analysis %>% pivot_wider(id_cols = CASEID, names_from = nv, values_from = c(CD4N, CD8N, A2) ) %>%
  select(!A2_2)

dat.full <- mice(dat, m=5, maxit=50, meth='pmm', seed=500)

dat = complete(dat.full, 1)

```



```{r gibbs_fn}
# Gibbs sampler for new parameter values
# input: old parameter values (theta, gamma, beta, sigsq), data (design, response)
# output: list of new sampled values for each parameter

sample.new = function(theta.old, gamma.old, beta.old, sigsq.old, design, resp) {
  
  p = ncol(design)
  # sample new theta
  # assumption: U(0,1) prior on theta/ binomial distribution on gamma (beta - binomial)
  
  theta.new = rbeta(1, shape1 = sum(gamma.old) + 1  ,shape2 = p - sum(gamma.old) + 1)

  # sample new gamma 
  # assumption: independent elements, fixed nu_0, nu_1

  pg = rep(0,p) # hold the gamma probabilities
  
  for(pred in 1:p) {
    a = (theta.new * dnorm(beta.old[pred],mean = 0, sd = nu_1))
    b = (1-theta.new) * dnorm(beta.old[pred],mean = 0, sd = nu_0)
    pg[pred] = a/(a+b)
  }
  
  gamma.new = rbinom(p, 1, prob = pg) # now, sample based on posterior probabilities
  
  # sample new beta
  # assume scale mixture prior and normal likelihood for response with sigma = sigma^2 * I
  M = (t(design) %*% design)*sigsq.old^-1 + diag(ifelse(gamma.new == 1, 1/nu_1, 1/nu_0)) 
  Minv = solve(M)
  meanvec = sigsq.old^-1 * Minv %*% t(design) %*% resp
  beta.new = rmvnorm(1, mean = meanvec, sigma = Minv)
  
  # sample new sigsq
  # assumptions: IG(.5, .5) prior on sigsq
  ss = sum ( (resp - design %*% array(beta.new, dim=p) )^2 )
  n = length(resp)
  sigsq.new = rgamma(1, (n+1)/2, (ss+1)/2)
  
  
  return(list(theta.new=theta.new, 
              gamma.new=gamma.new, 
              beta.new=beta.new,
              sigsq.new=sigsq.new))
}

```


```{r}

#attach(dat.f1)
set.seed(2)
nIter = 1000

nu_1 = 5
nu_0 = 0.3

p = 2 # covariate model design matrix dimension
pY = 4 # outcome model design matrix dimension

# array of parameters for each intermediate variable
# theta (1)/ gamma (p)/ beta (p)/ sigsq (1)

nCov = 2 # number of time-indexed covariates
params = array(.1, dim = c(2, nIter, 2 * p + 2)) # intermediate variables
paramsY = array(.1, dim = c(nIter, 2 * pY + 2))


for(it in 2:nIter) {
  # sample theta
  
  
  
  ############## sample CD4's #####################
  new.params = sample.new(theta.old = params[1, it-1, 1],
                          gamma.old = params[1, it-1, 2:(p+1)],
                          beta.old = params[1, it-1, (p+2):(2*p+1)],
                          sigsq.old = params[1, it-1, 2*p+2],
                          design = cbind(log(dat$CD4N_0), dat$A2_0),
                          resp = log(dat$CD4N_1) )
  
  params[1, it, 1] = new.params$theta.new
  params[1, it, 2:(p+1)] = new.params$gamma.new
  params[1, it, (p+2):(2*p+1)] = new.params$beta.new
  params[1, it, 2*p+2] = new.params$sigsq.new
  
  ############## sample CD8's #####################
  new.params = sample.new(theta.old = params[2, it-1, 1],
                        gamma.old = params[2, it-1, 2:(p+1)],
                        beta.old = params[2, it-1, (p+2):(2*p+1)],
                        sigsq.old = params[2, it-1, 2*p+2],
                        design = cbind(log(dat$CD8N_0), dat$A2_0),
                        resp = log(dat$CD8N_1) )
  
  params[2, it, 1] = new.params$theta.new
  params[2, it, 2:(p+1)] = new.params$gamma.new
  params[2, it, (p+2):(2*p+1)] = new.params$beta.new
  params[2, it, 2*p+2] = new.params$sigsq.new
  
  ############## sample Y's #######################
  pY = 4
  new.params = sample.new(theta.old = paramsY[it-1, 1],
                      gamma.old = paramsY[it-1, 2:(pY+1)],
                      beta.old = paramsY[it-1, (pY+2):(2*pY+1)],
                      sigsq.old = paramsY[it-1, 2*pY+2],
                      design = cbind(log(dat$CD4N_1), log(dat$CD8N_1), dat$A2_0, dat$A2_1),
                      resp = log(dat$CD4N_2) )
  
  paramsY[it, 1] = new.params$theta.new
  paramsY[it, 2:(pY+1)] = new.params$gamma.new
  paramsY[it, (pY+2):(2*pY+1)] = new.params$beta.new
  paramsY[it, 2*pY+2] = new.params$sigsq.new
  
}

```

```{r}
# completed dataset for each set of parameters
# RANDOM G
# augmented data set
n = nrow(dat)

dat$y11 = NA
dat$y00 = NA
dat$t1 = ifelse(dat$A2_0 == 1 & dat$A2_0 == 1, 1, 0)
dat$t0 = ifelse(dat$A2_0 == 0 & dat$A2_0 == 0, 1, 0)

# first, let's do this with the correct G
row = 100
ndraws = 5

diffs = array(0, dim = ndraws)

for(draw in 1:ndraws) {
  
  if ( params[1, row + draw, 3] == 1 ) { # if there is an edge from treatment to covariate, impute

    mx1 = cbind(log(dat$CD4N_0), 1) %*% params[1, row + draw, c(4,5)]  # XB (treated at time 1)
    X2draw1 = rnorm(n, mean = mx1, sd = params[1, row + draw, 6]) # fixed treatment to 1
    X2draw1 = ifelse(dat$A2_0 == 1, log(dat$CD4N_0), X2draw1)
    print(X2draw1)
    
    
    mx0 = cbind(log(dat$CD4N_0),0) %*% params[1, row + draw, c(4,5)]  # XB (treated at time 1)
    X2draw0 = rnorm(n, mean = mx0, sd = params[1, row + draw, 6]) # fixed treatment to 1
    X2draw0 = ifelse(dat$A2_0 == 0, log(dat$CD4N_0), X2draw0)

  
  } else { 
    
    X2draw1 = log(dat$CD4N_0)
    X2draw0 = log(dat$CD4N_0)
    
  }
  
  if ( params[2, row + draw, 3] == 1 ) { # if there is an edge from treatment to covariate, impute
  
    mz1 = cbind(log(dat$CD8N_0), 1) %*% params[2, row + draw, c(4,5)]  # XB (treated at time 1)
    Z2draw1 = rnorm(n, mean = mz1, sd = params[2, row + draw, 6]) # fixed treatment to 1
    Z2draw1 = ifelse(dat$A2_0 == 1, log(dat$CD8N_0), Z2draw1)
    
    
    mz0 = cbind(log(dat$CD8N_0), 0) %*% params[1, row + draw, c(4,5)]  # XB (treated at time 1)
    Z2draw0 = rnorm(n, mean = mz0, sd = params[1, row + draw, 6]) # fixed treatment to 1
    Z2draw0 = ifelse(dat$A2_0 == 0, log(dat$CD8N_0), Z2draw0)

  
  } else { 
    
    Z2draw1 = log(dat$CD8N_0)
    Z2draw0 = log(dat$CD4N_0)
    
    }

  
  
  
  
  my1 = cbind(X2draw1, Z2draw1, 1, 1) %*% paramsY[(row+draw),c(6:9)] # always treated
  Ydraw1 = rnorm(n, mean = my1, sd = paramsY[(row+draw), 10])
  
  my0 = cbind(X2draw0, Z2draw0, 0, 0) %*% paramsY[(row+draw),c(6:9)] # always treated
  Ydraw0 = rnorm(n, mean = my0, sd = paramsY[(row+draw), 10])

  
  dat$y11 = ifelse(dat$t1 == 1, log(dat$CD4N_2), Ydraw1)
  dat$y00 = ifelse(dat$t0 == 1, log(dat$CD4N_2), Ydraw0)
  
  #print(sum(dat$y11))
  diffs[draw] = sum(dat$y11 - dat$y00)/n
}

#hist(diffs)
#d.random = data.frame(diffs = diffs, g = "ran" )


```


